export interface Asset {
  id: string;
  code: string;
  title: string;
  description: string;
  brand: string;
  defaultCurrency?: string;
  price: number;
  priceOption: number;
  leasePeriodUnit?: number;
  count: number;
  countUnit: string;
  ownership: number;
  owner: any;
  ownerAgent: any;
  subCategory: string;
  location: string;
  city: string;
  region: string;
  postalCode: string;
  country: string;
  thumb: string;
  purpose: number;
  modelNo: string;
  status: number;
  life: number;
  customFields: any;
  wholeTransact: boolean;
  paymentOptions: any;
  isPublished?: boolean;
  publishedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
};
