export interface Request {
  uid: string,
  title: string,
  hiMsg: string,
  demander: any,
  demanderAgent: any,
  supplier: any,
  supplierAgent: any,
  reqType: number,
  price: number,
  priceDescription: string,
  detail: any,
  material?: any,
  fileName?: string,
  attachment_uri: string,
  status: number,
  conversation: string,
  contract: string,
  referralId: string,
  rejectReason?: string,
  history?: any,
  mode?: number,
  demanderSignCount?: number,
  supplierSignCount?: number,
  createdAt?: Date | string,
  updatedAt?: Date | string
};
